@startuml transaction1
title Send/Update Screening Information
skinparam actorStyle awesome

hide footbox

'!include ./style.iuml

actor "**Screening Information Provider**" as SIP
actor "**Screening Information Receiver**" as SIR

SIP --> SIR : Send/Update Screening Information\n (Batch)
activate SIR
SIR --> SIP: Feedback 


@enduml
