@startuml
title Submit Screening Information\n
skinparam actorStyle awesome

hide footbox

'!include ./style.iuml

actor "**Screening**\n**Information**\n**Provider**" as SIP
actor "**Screening**\n**Information**\n**Receiver**" as SIR

|||
SIP --> SIR : Submit Screening Information\n (Batch)
activate SIR
SIR --> SIP: Response 


@enduml
